### PR TITLE
Dockerized GitGrabber

### PR DESCRIPTION
**Pull request by AlekKras**
Created a Dockerfile to run GitGrabber from the Docker. Works fine, you can also push the image to the Docker hub for the future.

### CODE REVIEW

**Comment by rmarot** [comment]
Hi ! 
Thanks for the PR :) We will have a look at this quickly.

**Comment by rmarot** [comment]
Thanks again for your PR. After reviewing it sounds that your Dockerfile references "gitGrabber" directory (should be gitGraber) and that you renamed the files by prefixing with gitGraber their names. Could please double check on your side, and maybe push only the Dockerfile ? 

Many thanks

**Comment by AlekKras** [comment]
Just redid it. Submitted the Dockerfile. Sorry for the misspelling it.

**Comment by rmarot** [comment]
Hi @AlekKras 

Apologies for the delay ! Would it be possible to specify the command lines to build and run the container in the README file ? Maybe we could simplify the Dockerfile too ? (use a custom directory in the container filesystem rather than the root dir for example and use a lighter container like python:3 ? 

Thank you !

**Comment by rmarot** [comment]
Feel free to reopen PR if you update. Thank you !

**Pull request closed without merging**
